fix: git hooks

diff --git a/scripts/git-hooks/sh/pre-commit b/scripts/git-hooks/sh/pre-commit
--- a/scripts/git-hooks/sh/pre-commit
+++ b/scripts/git-hooks/sh/pre-commit
@@ -2,4 +2,9 @@
 
 ./gradlew ktlintCheck
 
+if [ $? -ne 0 ]; then
+  echo "Build failed. Aborting commit."
+  exit 1
+fi
+
 git add .
